/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

/**
 *
 * @author rayan
 */
public class TextInput extends javax.swing.JPanel {

    /**
     * Creates new form TextInput
     */
    PaintWindow myMaster;

    public TextInput(PaintWindow myMaster) {
        initComponents();
        this.myMaster = myMaster;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelText = new javax.swing.JPanel();
        buttonTextSubmit = new javax.swing.JButton();
        textFieldText = new javax.swing.JTextField();
        buttonTextCancel = new javax.swing.JButton();
        labelTextPrompt = new javax.swing.JLabel();

        panelText.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonTextSubmit.setText("Accept");
        buttonTextSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonTextSubmitMousePressed(evt);
            }
        });
        panelText.add(buttonTextSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        textFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTextActionPerformed(evt);
            }
        });
        panelText.add(textFieldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        buttonTextCancel.setText("Cancel");
        buttonTextCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextCancelActionPerformed(evt);
            }
        });
        panelText.add(buttonTextCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        labelTextPrompt.setText("Please enter text you wish to draw.");
        panelText.add(labelTextPrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelText, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTextSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTextSubmitMousePressed
        // TODO add your handling code here:
        myMaster.frameText.setVisible(false);
        myMaster.inputtedText = textFieldText.getText();
        if (myMaster.inputtedText != "") {
            myMaster.drawText = true;
        }
    }//GEN-LAST:event_buttonTextSubmitMousePressed

    private void textFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTextActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_textFieldTextActionPerformed

    private void buttonTextCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextCancelActionPerformed
        // TODO add your handling code here:
        myMaster.frameText.setVisible(false);
    }//GEN-LAST:event_buttonTextCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTextCancel;
    private javax.swing.JButton buttonTextSubmit;
    private javax.swing.JLabel labelTextPrompt;
    private javax.swing.JPanel panelText;
    private javax.swing.JTextField textFieldText;
    // End of variables declaration//GEN-END:variables
}
