/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

import java.awt.Color;

/**
 *
 * @author rayan
 */
public class ToolColor extends javax.swing.JPanel {

    /**
     * Creates new form ToolColor
     */
    PaintWindow myMaster;

    boolean buttonClicked;

    public ToolColor(PaintWindow myMaster) {
        initComponents();
        this.myMaster = myMaster;
    }

    public Color getColor() {
        return ToolColorChooser.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolColorChooser = new javax.swing.JColorChooser();
        buttonSubmitted = new javax.swing.JButton();

        buttonSubmitted.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonSubmitted.setText("Submit");
        buttonSubmitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmittedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ToolColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonSubmitted)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(buttonSubmitted)
                .addContainerGap())
        );

        ToolColorChooser.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmittedActionPerformed
        // TODO add your handling code here:

        if (myMaster.setBackgroundColor == true) {
            myMaster.canvasBackgroundColor(ToolColorChooser.getColor());
            myMaster.setBackgroundColor = false;
            System.out.println(myMaster.setBackgroundColor);
        } else {
            buttonClicked = true;
            myMaster.setColor(ToolColorChooser.getColor());
        }
        myMaster.hideColorPanel();
    }//GEN-LAST:event_buttonSubmittedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser ToolColorChooser;
    private javax.swing.JButton buttonSubmitted;
    // End of variables declaration//GEN-END:variables
}
